#!/bin/bash
build $1 $2 && build $1_gen $2 && build $1_brute $2 &&
for((i = 1; ; ++i)); do
    echo -e "\nTest Case "$i
    ./$1_gen $i > inp
    echo -e "===========\nINPUT\n-----"
    cat inp
    ./$1 < inp > out1
    echo -e "\nOUTPUT\n------"
    cat out1
    ./$1_brute < inp > out2
    echo -e "\nEXPECTED\n--------"
    cat out2
    echo ""
    diff -w out1 out2 || break
done
