filetype plugin indent on
set rnu wfw hls is ar aw wrap mouse=a

let mapleader=' '
im jk <esc>
tno jk <c-w>N
no <leader>d "_d
im {<cr> {<cr>}<esc>O
nn ff :let @+ = expand("%:p")<cr>
nn cd :cd %:h<cr>

au BufNewFile *.cpp -r ./template.cpp | 14

ca hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \| md5sum \| cut -c-6
