filetype plugin indent on
set rnu hls is ar aw wrap sb spr tm=300 mouse=a
hi CursorLine cterm=none

let mapleader = " "
im jk <esc>
tno jk <c-w>N
no <c-c> "+y
no <c-a> ggVG
no <leader>d "_d
im {<cr> {<cr>}<esc>O
nn <leader>f :let @+ = expand("%:p")<cr>
nn <leader>cd :cd %:h<cr>
nn <leader>b :ls<cr>:b

au BufNewFile *.cpp -r ./template.cpp | 14

ca hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \| md5sum \| cut -c-6
